/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swingbuilder;

import org.junit.Test;

import javax.swing.*;

import static com.insilicalabs.swingbuilder.Creators.frame;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void canCreateFrame() {
        JFrame frame = frame();
        assertTrue("can create frame", frame!=null);
    }
}
